### ISSUE TITLE
Storage Class watch: Invalid value for provisioner

### ISSUE THREAD

**Issue by bzurkowski** [openrca/orca#29]
```
06:51:26 probe.1 | Unhandled exception
06:51:26 probe.1 | Traceback (most recent call last):
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/cotyledon/_utils.py", line 95, in exit_on_exception
06:51:26 probe.1 |     yield
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/cotyledon/_service.py", line 139, in _run
06:51:26 probe.1 |     self.run()
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/probe.py", line 50, in run
06:51:26 probe.1 |     probe.run()
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/probe.py", line 141, in run
06:51:26 probe.1 |     self._upstream_proxy.get_events(handler=self)
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/infra/k8s/upstream.py", line 26, in get_events
06:51:26 probe.1 |     for event in self._client.watch():
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/common/clients/k8s/client.py", line 90, in watch
06:51:26 probe.1 |     for event in self._watch_resource():
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 145, in stream
06:51:26 probe.1 |     yield self.unmarshal_event(line, return_type)
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 96, in unmarshal_event
06:51:26 probe.1 |     js['object'] = self._api_client.deserialize(obj, return_type)
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 256, in deserialize
06:51:26 probe.1 |     return self.__deserialize(data, response_type)
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 295, in __deserialize
06:51:26 probe.1 |     return self.__deserialize_model(data, klass)
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 638, in __deserialize_model
06:51:26 probe.1 |     instance = klass(**kwargs)
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/models/v1_storage_class.py", line 88, in __init__
06:51:26 probe.1 |     self.provisioner = provisioner
06:51:26 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/models/v1_storage_class.py", line 274, in provisioner
06:51:26 probe.1 |     raise ValueError("Invalid value for `provisioner`, must not be `None`")  # noqa: E501
06:51:26 probe.1 | ValueError: Invalid value for `provisioner`, must not be `None`
```

**Comment by bzurkowski** [comment]
Similar error encountered for stateful set watch:
```
08:14:53 probe.1 | Unhandled exception
08:14:53 probe.1 | Traceback (most recent call last):
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/cotyledon/_utils.py", line 95, in exit_on_exception
08:14:53 probe.1 |     yield
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/cotyledon/_service.py", line 139, in _run
08:14:53 probe.1 |     self.run()
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/probe.py", line 50, in run
08:14:53 probe.1 |     probe.run()
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/probe.py", line 141, in run
08:14:53 probe.1 |     self._upstream_proxy.get_events(handler=self)
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/infra/k8s/upstream.py", line 26, in get_events
08:14:53 probe.1 |     for event in self._client.watch():
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/common/clients/k8s/client.py", line 90, in watch
08:14:53 probe.1 |     for event in self._watch_resource():
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 145, in stream
08:14:53 probe.1 |     yield self.unmarshal_event(line, return_type)
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 96, in unmarshal_event
08:14:53 probe.1 |     js['object'] = self._api_client.deserialize(obj, return_type)
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 256, in deserialize
08:14:53 probe.1 |     return self.__deserialize(data, response_type)
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 295, in __deserialize
08:14:53 probe.1 |     return self.__deserialize_model(data, klass)
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 636, in __deserialize_model
08:14:53 probe.1 |     kwargs[attr] = self.__deserialize(value, attr_type)
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 295, in __deserialize
08:14:53 probe.1 |     return self.__deserialize_model(data, klass)
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 638, in __deserialize_model
08:14:53 probe.1 |     instance = klass(**kwargs)
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/models/v1_stateful_set_status.py", line 83, in __init__
08:14:53 probe.1 |     self.replicas = replicas
08:14:53 probe.1 |   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/models/v1_stateful_set_status.py", line 248, in replicas
08:14:53 probe.1 |     raise ValueError("Invalid value for `replicas`, must not be `None`")  # noqa: E501
08:14:53 probe.1 | ValueError: Invalid value for `replicas`, must not be `None`
```

**Comment by bzurkowski** [comment]
Known issue in Kubernetes Python client. Will be fixed in v12.0.0.
