### ISSUE TITLE
Cannot deploy OpenRCA with arrangoDB (CrashLoopBackOff)

### ISSUE THREAD

**Issue by aleksandra-galara** [openrca/orca#52]
After deploying OpenRCA with arangoDB, orca pod ended up in CrashLoopBackOff with logs below:

```
07:34:24 system  | SIGTERM received
07:34:24 system  | sending SIGTERM to api.1 (pid 9)
07:34:24 system  | sending SIGTERM to probe.1 (pid 10)
07:34:28 probe.1 | Unhandled exception
07:34:28 probe.1 | Traceback (most recent call last):
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/cotyledon/_utils.py", line 95, in exit_on_exception
07:34:28 probe.1 |     yield
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/cotyledon/_service.py", line 139, in _run
07:34:28 probe.1 |     self.run()
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/probe.py", line 47, in run
07:34:28 probe.1 |     probe = self._initialize_probe()
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/probe.py", line 54, in _initialize_probe
07:34:28 probe.1 |     return probe_module.get(self._graph)
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/topology/probe.py", line 43, in _graph
07:34:28 probe.1 |     self.__graph = graph.Graph.get(self._graph_lock)
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/graph/graph.py", line 156, in get
07:34:28 probe.1 |     driver = drivers.DriverFactory.get(CONFIG.graph.driver)
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/common/config.py", line 32, in __getattr__
07:34:28 probe.1 |     return self._get(name)
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/common/config.py", line 44, in _get
07:34:28 probe.1 |     return getattr(self._cache, name)
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/common/config.py", line 40, in _cache
07:34:28 probe.1 |     self.__cache = self._parser.parse(self._path)
07:34:28 probe.1 |   File "/usr/local/lib/python3.7/site-packages/orca/common/config.py", line 64, in parse
07:34:28 probe.1 |     raise exceptions.ConfigParseError(errors=validator.errors)
07:34:28 probe.1 | orca.exceptions.ConfigParseError: Error while parsing configuration: {'graph': [{'arangodb': ['unknown field']}], 'ingestors': ['unknown field'], 'logging': ['unknown field'], 'probes': ['unknown field']}.
07:34:28 api.1   | Unhandled exception
07:34:28 api.1   | Traceback (most recent call last):
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/cotyledon/_utils.py", line 95, in exit_on_exception
07:34:28 api.1   |     yield
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/cotyledon/_service.py", line 139, in _run
07:34:28 api.1   |     self.run()
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/orca/api/manager.py", line 47, in run
07:34:28 api.1   |     app = self._initialize_application()
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/orca/api/manager.py", line 56, in _initialize_application
07:34:28 api.1   |     app.register_blueprint(api.initialize(self._graph))
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/orca/api/manager.py", line 42, in _graph
07:34:28 api.1   |     self.__graph = graph.Graph.get(self._graph_lock)
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/orca/graph/graph.py", line 156, in get
07:34:28 api.1   |     driver = drivers.DriverFactory.get(CONFIG.graph.driver)
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/orca/common/config.py", line 32, in __getattr__
07:34:28 api.1   |     return self._get(name)
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/orca/common/config.py", line 44, in _get
07:34:28 api.1   |     return getattr(self._cache, name)
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/orca/common/config.py", line 40, in _cache
07:34:28 api.1   |     self.__cache = self._parser.parse(self._path)
07:34:28 api.1   |   File "/usr/local/lib/python3.7/site-packages/orca/common/config.py", line 64, in parse
07:34:28 api.1   |     raise exceptions.ConfigParseError(errors=validator.errors)
07:34:28 api.1   | orca.exceptions.ConfigParseError: Error while parsing configuration: {'graph': [{'arangodb': ['unknown field']}], 'ingestors': ['unknown field'], 'logging': ['unknown field'], 'probes': ['unknown field']}.
07:34:28 system  | probe.1 stopped (rc=0)
07:34:28 system  | api.1 stopped (rc=0)
```

**Comment by romoreira** [comment]
Are there any updates regarding this issue? I'm experiencing something like this.
